Invoke lambda deployment type
guardian/riff-raff pull request #630
Opened 2021-06-15 15:13 UTC by rhystmills

## What does this change?

Adds Invoke Lambda deployment type.

## How to test

## How can we measure success?

## Have we considered potential risks?

## Images

## Accessibility

- [ ] [Tested with screen reader](https://www.theguardian.design/2a1e5182b/p/6691bb-accessibility/t/558398)
- [ ] [Navigable with keyboard](https://www.theguardian.design/2a1e5182b/p/6691bb-accessibility/t/39894d)
- [ ] [Colour contrast passed](https://www.theguardian.design/2a1e5182b/p/6691bb-accessibility/t/92b913)
- [ ] [The change doesn't use only colour to convey meaning](https://www.theguardian.design/2a1e5182b/p/6691bb-accessibility/t/29032f)

2022-10-05 11:00 UTC, nicl commented
@rhystmills I am going to close this as it's been over a year but obviously feel free to reopen if still keen to get merged.

2022-10-20 13:30 UTC, twrichards commented
I missed this being closed, I'd really rather this wasn't closed - @rhystmills and I spent probably a year of weekly pairing sessions getting this whole mechanism working.
@guardian/developer-experience please can we resume discussions to get this merged, so TX etc. can benefit from version control in Braze (kind of a big deal that they don't have it)

2022-11-23 10:25 UTC, akash1810 commented
Converting this to draft. This PR is still valuable, however IIUC we're discussing if the change in processes for the retention team are possible? The PR is also not mergeable yet, as it's got conflicts.

Lastly, draft PRs are not reported by [guardian/actions-prnouncer](https://github.com/guardian/actions-prnouncer).

2022-12-08 15:59 UTC, twrichards commented
@rhystmills and I met with TX (CC @tjmw ) and there seems to be appetite for this `braze-publish` deployment type (see https://riffraff.code.dev-gutools.co.uk/docs/magenta-lib/types#brazepublish), so we've opened this back up for review 🙏 (having rebased and resolved all the merge conflicts, twice). CC @kenoir @akash1810

2022-12-12 13:56 UTC, akash1810 reviewed
My knowledge of this service isn't that detailed. Some tests against these new deployment types would increase confidence; could we add some?

2022-12-12 13:56 UTC, akash1810 commented on magenta-lib/src/main/scala/magenta/deployment_type/BrazePublish.scala
> +    s"Invokes Lambda `${brazePublishLambdaNameMinusStage}` (with the STAGE appended). This Lambda publishes content blocks to the target Braze environment (only if there are changes)."
Does this mean we're invoking a lambda by name and _not_ via tag lookup? If so, is that desirable? (I'd suggest it isn't).

2022-12-12 13:56 UTC, akash1810 commented on magenta-lib/src/main/scala/magenta/deployment_type/LambdaDeploymentType.scala
> +trait LambdaDeploymentType[LAMBDA_TASK_PRECURSOR <: LambdaTaskPrecursor]
Ah, Scala, you're syntax is super accessible...

2022-12-12 13:56 UTC, akash1810 commented on magenta-lib/src/main/scala/magenta/deployment_type/LambdaInvoke.scala
> +      LambdaFunctionName(s"$stackNamePrefix$name$stage"),
minor: can drop the interpolation here.

2022-12-12 13:56 UTC, akash1810 commented
> The primary motivation for this PR was to facilitate version control and automated deployment of Braze content blocks, making use of [`guardian/braze-version-control-service`](https://github.com/guardian/braze-version-control-service).

Could we update the README for https://github.com/guardian/braze-version-control-service, it's currently empty making maintainability difficult.

2022-12-16 17:16 UTC, nicl commented on magenta-lib/src/main/scala/magenta/deployment_type/DeploymentType.scala
> +  def paramsToHide = Seq.empty[Param[_]]
I think this is a standard part of the general `DeploymentType` - it allows one deployment type that extends from another to hide certain params that are not needed in the new type.

2022-12-16 17:32 UTC, nicl requested changes
The functionality seems 👍 

I would like to recommend removing the whole `LAMBDA_TASK_PRECURSOR` pattern (and associated `buildLambdaTaskPrecursor` methods). It feels a bit abstract and unnecessary. 

The aim seems to be to provide a very general way to take the common params and generate what the specific deployment requires. But in this case I think being more concrete would be much clearer and simpler. I.e. the common requirement is really to get back a lambda function *name* here, which can then be operated on. So why not simply add a (static) method on the `LambdaDeploymentType` trait called `getTargetFunction` or something?

2023-01-23 09:27 UTC, akash1810 commented
This needs rebasing following the merge of https://github.com/guardian/riff-raff/pull/945. As a result, converting to draft so it doesn't appear in the daily report from https://github.com/guardian/actions-prnouncer.

2023-06-01 06:01 UTC, closed without merging